-- -- 1. Crear el catálogo de sucursales
-- CREATE TABLE SUCURSALES (
--     ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     NOMBRE VARCHAR2(50) NOT NULL,
--     ESTADO NUMBER(1) DEFAULT 1 NOT NULL
-- );

-- -- 2. Insertar datos iniciales
-- INSERT INTO SUCURSALES (NOMBRE) VALUES ('Central');
-- INSERT INTO SUCURSALES (NOMBRE) VALUES ('Norte');
-- INSERT INTO SUCURSALES (NOMBRE) VALUES ('Sur');
-- COMMIT;

-- -- 3. Crear la columna para la llave foránea en el inventario
-- ALTER TABLE INVENTARIO_MEDICAMENTOS ADD SUCURSAL_ID NUMBER;

-- -- 4. Migrar los datos (traducir el texto al ID correspondiente)
-- UPDATE INVENTARIO_MEDICAMENTOS 
-- SET SUCURSAL_ID = (SELECT ID FROM SUCURSALES WHERE SUCURSALES.NOMBRE = INVENTARIO_MEDICAMENTOS.SUCURSAL);
-- COMMIT;

-- -- 5. Hacer la columna obligatoria, borrar la vieja de texto y aplicar la restricción de Llave Foránea
-- ALTER TABLE INVENTARIO_MEDICAMENTOS MODIFY SUCURSAL_ID NOT NULL;
-- ALTER TABLE INVENTARIO_MEDICAMENTOS DROP COLUMN SUCURSAL;
-- ALTER TABLE INVENTARIO_MEDICAMENTOS ADD CONSTRAINT FK_INV_SUCURSAL FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSALES(ID);

-- INSERT INTO SUCURSALES (NOMBRE) VALUES ('Este'); COMMIT;

SELECT * FROM SUCURSALES;