-- 1. Crear la tabla
-- CREATE TABLE INVENTARIO_MEDICAMENTOS (
--     ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     NOMBRE VARCHAR2(100) NOT NULL,
--     STOCK NUMBER NOT NULL,
--     SUCURSAL VARCHAR2(50) NOT NULL
-- );

-- -- 2. Insertar los datos de prueba
-- INSERT INTO INVENTARIO_MEDICAMENTOS (NOMBRE, STOCK, SUCURSAL) 
-- VALUES ('Paracetamol 500mg', 150, 'Central');

-- INSERT INTO INVENTARIO_MEDICAMENTOS (NOMBRE, STOCK, SUCURSAL) 
-- VALUES ('Amoxicilina 250mg', 45, 'Norte');

-- INSERT INTO INVENTARIO_MEDICAMENTOS (NOMBRE, STOCK, SUCURSAL) 
-- VALUES ('Ibuprofeno 400mg', 12, 'Sur');

-- -- 3. Confirmar la transacción (Indispensable en Oracle)
-- COMMIT;


SELECT * FROM INVENTARIO_MEDICAMENTOS;

-- UPDATE INVENTARIO_MEDICAMENTOS
-- SET Estado = 1
-- WHERE ID='6';

-- commit;


-- ALTER TABLE INVENTARIO_MEDICAMENTOS ADD ESTADO NUMBER(1) DEFAULT 1 NOT NULL;