-- CREATE TABLE USUARIOS (
--     ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     NOMBRE_COMPLETO VARCHAR2(100) NOT NULL,
--     EMAIL VARCHAR2(100) UNIQUE NOT NULL,
--     PASSWORD_HASH VARCHAR2(255) NOT NULL,
--     ROL VARCHAR2(20) DEFAULT 'CAJERO' NOT NULL,
--     ESTADO NUMBER(1) DEFAULT 1 NOT NULL
-- );

-- COMMIT;


SELECT * FROM USUARIOS;